Traceback (most recent call last):
  File "/home/yinan/book-env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/yinan/book-env/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Problem.draw_tours(sol)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_6466/3014936520.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mProblem[0m[0;34m.[0m[0mdraw_tours[0m[0;34m([0m[0msol[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_6466/703988465.py[0m in [0;36mdraw_tours[0;34m(tours)[0m
[1;32m    128[0m                 [0;32mif[0m [0mi[0m [0;34m==[0m [0mlen[0m[0;34m([0m[0mtour[0m[0;34m)[0m [0;34m-[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    129[0m                     [0mi[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 130[0;31m                 [0mfolium[0m[0;34m.[0m[0mMarker[0m[0;34m([0m[0mlocation[0m[0;34m=[0m[0mloc[0m[0;34m,[0m [0micon[0m[0;34m=[0m[0mfolium[0m[0;34m.[0m[0mIcon[0m[0;34m([0m[0mcolor[0m[0;34m=[0m[0;34m'white'[0m[0;34m,[0m [0micon_color[0m[0;34m=[0m[0;34m'white'[0m[0;34m)[0m[0;34m)[0m[0;34m.[0m[0madd_to[0m[0;34m([0m[0mm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    131[0m                 [0mfolium[0m[0;34m.[0m[0mMarker[0m[0;34m([0m[0mlocation[0m[0;34m=[0m[0mlist[0m[0;34m([0m[0mv[0m[0;34m.[0m[0mcoordinates[0m[0;34m)[0m[0;34m[[0m[0;34m:[0m[0;34m:[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m,[0m  [0micon[0m[0;34m=[0m[0mnumber_DivIcon[0m[0;34m([0m[0mcolor[0m[0;34m,[0m[0mi[0m[0;34m)[0m[0;34m)[0m[0;34m.[0m[0madd_to[0m[0;34m([0m[0mm[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    132[0m                 [0mr[0m [0;34m=[0m [0mu[0m[0;34m.[0m[0mroute_to[0m[0;34m([0m[0mv[0m[0;34m)[0m[0;34m[[0m[0;34m'coords'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'loc' is not defined
NameError: name 'loc' is not defined

